name: 'retail_analytics'
version: '1.0.0'
config-version: 2

profile: 'retail_analytics'

model-paths: ["data_warehouse/models"]

models:
  retail_analytics:
    dim:
      +materialized: table
    fact:
      +materialized: table
